//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxisSmartHomeControlSystemMVCDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceTmp
    {
        public int ID { get; set; }
        public string DeviceID { get; set; }
        public string DeviceSN { get; set; }
        public string DeviceDefaultName { get; set; }
        public string Description { get; set; }
        public bool IsDeviceNameUpdated { get; set; }
        public string UpdatedDeviceName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
