//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxisSmartHomeControlSystemMVCDemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RexliteDBEntities : DbContext
    {
        public RexliteDBEntities()
            : base("name=RexliteDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADSLSetting> ADSLSettings { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<DeviceTmp> DeviceTmps { get; set; }
        public virtual DbSet<LocationSetting> LocationSettings { get; set; }
        public virtual DbSet<MiscLookup> MiscLookups { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    
        public virtual ObjectResult<GetUserByUserEmail_Result> GetUserByUserEmail(string userEmail)
        {
            var userEmailParameter = userEmail != null ?
                new ObjectParameter("UserEmail", userEmail) :
                new ObjectParameter("UserEmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserByUserEmail_Result>("GetUserByUserEmail", userEmailParameter);
        }
    
        public virtual ObjectResult<GetUserRole_Result> GetUserRole()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserRole_Result>("GetUserRole");
        }
    }
}
